branches:
  only:
    - master
    - production
  except:
    - gh-pages

matrix:
  fast_finish: true # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

platform: Any CPU
configuration: Release
build:
  parallel: true
  project: toast.sln
  verbosity: detailed
